apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: breaklinux/kaniko-project:executor-debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
      - name: workspace-volume
        mountPath: /home/jenkins/agent
        readOnly: false
  - name: jnlp
    image: breaklinux/jenkins:inbound-agent_3142.vcfca_0cd92128-1
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
    volumeMounts:
      - mountPath: "/home/jenkins/agent"
        name: "workspace-volume"
        readOnly: false
      - mountPath: "/root/.kube"
        name: "kube-config-volume"
        readOnly: true
      - mountPath: "/bin/kubectl"
        name: "kubectl-binary-volume"
        readOnly: true
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: registry-secrete
          items:
          - key: .dockerconfigjson
            path: config.json
  - name: workspace-volume
    emptyDir: {}
  - name: kube-config-volume
    hostPath:
      path: /root/.kube
      type: Directory
  - name: kubectl-binary-volume
    hostPath:
      path: /bin/kubectl
      type: File
